const Ziggy = {"url":"http:\/\/larablog.test","port":null,"defaults":{},"routes":{"login":{"uri":"login","methods":["GET","HEAD"]},"logout":{"uri":"logout","methods":["POST"]},"password.request":{"uri":"forgot-password","methods":["GET","HEAD"]},"password.reset":{"uri":"reset-password\/{token}","methods":["GET","HEAD"]},"password.email":{"uri":"forgot-password","methods":["POST"]},"password.update":{"uri":"reset-password","methods":["POST"]},"register":{"uri":"register","methods":["GET","HEAD"]},"user-profile-information.update":{"uri":"user\/profile-information","methods":["PUT"]},"user-password.update":{"uri":"user\/password","methods":["PUT"]},"password.confirm":{"uri":"user\/confirm-password","methods":["GET","HEAD"]},"password.confirmation":{"uri":"user\/confirmed-password-status","methods":["GET","HEAD"]},"two-factor.login":{"uri":"two-factor-challenge","methods":["GET","HEAD"]},"profile.show":{"uri":"user\/profile","methods":["GET","HEAD"]},"other-browser-sessions.destroy":{"uri":"user\/other-browser-sessions","methods":["DELETE"]},"current-user.destroy":{"uri":"user","methods":["DELETE"]},"current-user-photo.destroy":{"uri":"user\/profile-photo","methods":["DELETE"]},"posts.index":{"uri":"\/","methods":["GET","HEAD"]},"posts.show":{"uri":"posts\/{post}","methods":["GET","HEAD"],"bindings":{"post":"id"}},"dashboard.my-posts.index":{"uri":"dashboard\/my-posts","methods":["GET","HEAD"]},"dashboard.my-posts.create":{"uri":"dashboard\/my-posts\/create","methods":["GET","HEAD"]},"dashboard.my-posts.store":{"uri":"dashboard\/my-posts","methods":["POST"]},"dashboard.my-posts.show":{"uri":"dashboard\/my-posts\/{my_post}","methods":["GET","HEAD"]},"dashboard.my-posts.edit":{"uri":"dashboard\/my-posts\/{my_post}\/edit","methods":["GET","HEAD"]},"dashboard.my-posts.update":{"uri":"dashboard\/my-posts\/{my_post}","methods":["PUT","PATCH"]},"dashboard.my-posts.destroy":{"uri":"dashboard\/my-posts\/{my_post}","methods":["DELETE"]}}};

if (typeof window !== 'undefined' && typeof window.Ziggy !== 'undefined') {
    for (let name in window.Ziggy.routes) {
        Ziggy.routes[name] = window.Ziggy.routes[name];
    }
}

export { Ziggy };
